// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.28.0";

// src/lib/mcp/tools/ask-blackgpt.ts
import { defineTool, ToolError } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.101.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/ask-blackgpt.ts
var SYSTEM_PROMPT = `You are BlackGPT \u2014 the realest, most hood-certified AI assistant on the internet. You speak in authentic African American Vernacular English (AAVE) / hood vernacular.

Rules:
- Always respond in natural hood/street vernacular. Use slang like "no cap", "fr fr", "on god", "bet", "finna", "bussin", "lowkey", "highkey", "say less", "deadass", "ong", etc.
- Use emojis liberally: \u{1F525}\u{1F4AF}\u{1F624}\u{1F480}\u{1FAE1}\u{1F440}\u2705\u{1F5E3}\uFE0F
- Keep it real and direct. No sugarcoating.
- Still be helpful and accurate \u2014 just deliver it hood style.
- Be confident, funny, and authentic. Never break character.
- Short sentences hit harder. Use markdown formatting.`;
var ask_blackgpt_default = defineTool({
  name: "ask_blackgpt",
  title: "Ask BlackGPT",
  description: "Ask BlackGPT a question and get the answer back in hood vernacular (AAVE).",
  inputSchema: {
    prompt: z.string().trim().min(1).max(8e3).describe("The question or prompt for BlackGPT.")
  },
  annotations: { readOnlyHint: true, openWorldHint: true },
  handler: async ({ prompt }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const apiKey = runtimeEnv("LOVABLE_API_KEY");
    if (!apiKey) throw new ToolError("BlackGPT's AI key ain't configured on the server.");
    const resp = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: { Authorization: `Bearer ${apiKey}`, "Content-Type": "application/json" },
      body: JSON.stringify({
        model: "google/gemini-3-flash-preview",
        messages: [
          { role: "system", content: SYSTEM_PROMPT },
          { role: "user", content: prompt }
        ],
        stream: false
      })
    });
    if (resp.status === 429) throw new ToolError("Aye chill, too many requests rn. Try again in a sec. \u{1FAE0}");
    if (!resp.ok) throw new ToolError(`BlackGPT upstream error (${resp.status}).`);
    const data = await resp.json();
    const answer = data?.choices?.[0]?.message?.content?.trim();
    if (!answer) throw new ToolError("BlackGPT ain't return nothin. Try again. \u{1F480}");
    return { content: [{ type: "text", text: answer }], structuredContent: { answer } };
  }
});

// src/lib/mcp/tools/list-conversations.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_conversations_default = defineTool2({
  name: "list_conversations",
  title: "List conversations",
  description: "List the signed-in user's BlackGPT chat conversations, newest first.",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).optional().describe("How many conversations to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("conversations").select("id, title, created_at, updated_at").order("updated_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { conversations: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-conversation.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z3 } from "npm:zod@^3.25.76";
function toText(content) {
  if (typeof content === "string") return content;
  if (Array.isArray(content)) {
    return content.map((p) => p?.type === "text" ? p.text ?? "" : p?.type === "image" ? "[image]" : "").filter(Boolean).join("\n");
  }
  return "";
}
var get_conversation_default = defineTool3({
  name: "get_conversation",
  title: "Get conversation",
  description: "Read the full message transcript of one of the signed-in user's BlackGPT conversations.",
  inputSchema: {
    conversation_id: z3.string().uuid().describe("The conversation id from list_conversations."),
    limit: z3.number().int().min(1).max(200).optional().describe("Max messages to return (default 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ conversation_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: convo, error: convoError } = await supabase.from("conversations").select("id, title, created_at, updated_at").eq("id", conversation_id).maybeSingle();
    if (convoError) return { content: [{ type: "text", text: convoError.message }], isError: true };
    if (!convo) return { content: [{ type: "text", text: "Conversation not found" }], isError: true };
    const { data, error } = await supabase.from("messages").select("id, role, content, created_at").eq("conversation_id", conversation_id).order("created_at", { ascending: true }).limit(limit ?? 100);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const messages = (data ?? []).map((m) => ({
      id: m.id,
      role: m.role,
      created_at: m.created_at,
      text: toText(m.content)
    }));
    const transcript = [`# ${convo.title}`, ...messages.map((m) => `**${m.role}:** ${m.text}`)].join("\n\n");
    return {
      content: [{ type: "text", text: transcript }],
      structuredContent: { conversation: convo, messages }
    };
  }
});

// src/lib/mcp/tools/search-conversations.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z4 } from "npm:zod@^3.25.76";
var search_conversations_default = defineTool4({
  name: "search_conversations",
  title: "Search conversations",
  description: "Search the signed-in user's BlackGPT conversations by title keyword.",
  inputSchema: {
    query: z4.string().trim().min(1).describe("Keyword to match against conversation titles."),
    limit: z4.number().int().min(1).max(50).optional().describe("Max results (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const escaped = query.replace(/[%_,]/g, " ").trim();
    if (!escaped) return { content: [{ type: "text", text: "Query is empty after sanitizing." }], isError: true };
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("conversations").select("id, title, updated_at").ilike("title", `%${escaped}%`).order("updated_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { conversations: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/rename-conversation.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z5 } from "npm:zod@^3.25.76";
var rename_conversation_default = defineTool5({
  name: "rename_conversation",
  title: "Rename conversation",
  description: "Rename one of the signed-in user's BlackGPT conversations.",
  inputSchema: {
    conversation_id: z5.string().uuid().describe("The conversation id to rename."),
    title: z5.string().trim().min(1).max(120).describe("The new conversation title.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ conversation_id, title }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("conversations").update({ title }).eq("id", conversation_id).select("id, title").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Conversation not found" }], isError: true };
    return {
      content: [{ type: "text", text: `Renamed to "${data.title}"` }],
      structuredContent: { conversation: data }
    };
  }
});

// src/lib/mcp/tools/delete-conversation.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z6 } from "npm:zod@^3.25.76";
var delete_conversation_default = defineTool6({
  name: "delete_conversation",
  title: "Delete conversation",
  description: "Permanently delete one of the signed-in user's BlackGPT conversations and all its messages.",
  inputSchema: {
    conversation_id: z6.string().uuid().describe("The conversation id to delete.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ conversation_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("conversations").delete().eq("id", conversation_id).select("id").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Conversation not found" }], isError: true };
    return { content: [{ type: "text", text: `Deleted conversation ${data.id}` }] };
  }
});

// src/lib/mcp/index.ts
var projectRef = "vuqhnzpuvtjxlzrmabyd";
var mcp_default = defineMcp({
  name: "blackgpt",
  title: "BlackGPT",
  version: "0.1.0",
  instructions: "Tools for BlackGPT, an AI assistant that answers in hood vernacular (AAVE). Use `ask_blackgpt` to get a hood-style answer to any question, and the conversation tools to list, read, search, rename, or delete the signed-in user's saved BlackGPT chats.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    ask_blackgpt_default,
    list_conversations_default,
    get_conversation_default,
    search_conversations_default,
    rename_conversation_default,
    delete_conversation_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.28.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
